<?php
return [
	'post_type' => 'post-type',
	'args'      => [
		'label'               => __( '', 'starter-theme' ),
		'labels'              => [
			'name'                  => __( '', 'starter-theme' ),
			'singular_name'         => __( '', 'starter-theme' ),
			'add_new'               => __( '', 'starter-theme' ),
			'add_new_item'          => __( '', 'starter-theme' ),
			'edit_item'             => __( '', 'starter-theme' ),
			'new_item'              => __( '', 'starter-theme' ),
			'view_item'             => __( '', 'starter-theme' ),
			'search_items'          => __( '', 'starter-theme' ),
			'not_found'             => __( '', 'starter-theme' ),
			'not_found_in_trash'    => __( '', 'starter-theme' ),
			'parent_item_colon'     => __( '', 'starter-theme' ),
			'menu_name'             => __( '', 'starter-theme' ),
			'all_items'             => __( '', 'starter-theme' ),
			'archives'              => __( '', 'starter-theme' ),
			'insert_into_item'      => __( '', 'starter-theme' ),
			'uploaded_to_this_item' => __( '', 'starter-theme' ),
			'featured_image'        => __( '', 'starter-theme' ),
			'set_featured_image'    => __( '', 'starter-theme' ),
			'remove_featured_image' => __( '', 'starter-theme' ),
			'use_featured_image'    => __( '', 'starter-theme' ),
			'filter_items_list'     => __( '', 'starter-theme' ),
			'items_list_navigation' => __( '', 'starter-theme' ),
			'items_list'            => __( '', 'starter-theme' ),
			'name_admin_bar'        => __( '', 'starter-theme' ),
			'view_items'            => __( '', 'starter-theme' ),
			'attributes'            => __( '', 'starter-theme' ),
		],
		'description'         => '',
		'public'              => true,
		'publicly_queryable'  => true,
		'exclude_from_search' => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'show_in_rest'        => true,
		'menu_position'       => 4,
		'menu_icon'           => '',
		'capability_type'     => '',
		'map_meta_cap'        => true,
		'hierarchical'        => false,
		'supports'            => [],
		'taxonomies'          => [],
		'has_archive'         => false,
		'rewrite'             => [],
		'query_var'           => true,
		'can_export'          => true,
	]
];
